version: '3'
services:
  web:
    build: .
    volumes:
      - .:/app
      - "~/.ssh:/home/app/.ssh"
      - "~/.aws:/home/app/.aws"
      - "~/.gitconfig:/home/app/.gitconfig"
      - app:/home/app
    working_dir: /app
    environment:
      MIX_BUILD_ROOT: /home/app/_build
      MIX_DEPS_PATH: /home/app/deps
volumes:
  app: